export const GYMS = [
  {
    id: 0,
    name: "2nd Gear Brazilian Jiu-Jitsu",
    featured: false,
    description: "Professor Kenneth Brown (Black Belt) ",
    address: "8730 Cherry Ln Ste 14, Laurel, MD 20707",
    phone: "(240) 786-5553",
  },
  {
    id: 1,
    name: "Agoge Brazilian Jiu Jitsu",
    featured: false,
    description: "Professor Joao Paulo Ferreira (Black Belt)",
    address: "474C Ritchie Hwy, Severna Park, MD 21146",
    phone: "(410) 415-3536",
  },
  {
    id: 2,
    name: "Calvert MMA Academy",
    featured: false,
    description: "Professor Jim Thrift (3rd Degree Black Belt)",
    address: "25 Dalrymple Rd, Sunderland, MD 20689",
    phone: "(410) 257-5425",
  },
  {
    id: 3,
    name: "Capital MMA & Elite Fitness",
    featured: false,
    description: "Jeremy Lafreniere (Black Belt)",
    address: "6836 New Hampshire Ave, Takoma Park, MD 20912",
    phone: "(301) 388-5020",
  },
  {
    id: 4,
    name: "Conquest Martial Arts & Fitness",
    featured: false,
    description: "Professor Vicente Junior (4th Degree)",
    address: "311 Serendipity Dr, Millersville, MD 21108",
    phone: "(443) 668-9769",
  },
  {
    id: 5,
    name: "Crazy 88 Mixed Martial Arts",
    featured: false,
    description: "Professor Tim Spriggs (Black Belt)",
    address: "7024 Troy Hill Dr Suite L, Elkridge, MD 21075",
    phone: "(443) 283-1450",
  },
  {
    id: 6,
    name: "Form Jiu Jitsu Academy",
    featured: false,
    description: "Rick Slomba (Black Belt)",
    address: "3700 O'Donnell St #240, Baltimore, MD 21224",
    phone: "(443) 301-6867",
  },
  {
    id: 7,
    name: "Gracie Jiu-Jitsu Maryland",
    featured: false,
    description: "Professor Mike Stewart Jr. (Black Belt)",
    address: "9570 Berger Rd, Columbia, MD 21046",
    phone: "(443) 605-3775",
  },
  {
    id: 8,
    name: "Kogen Dojo - Annapolis",
    featured: false,
    description: "Robert Van Valkenburgh (Black Belt)",
    address: "1912 Forest Dr Suite 2B, Annapolis, MD 21401",
    phone: "(240) 490-3352",
  },
  {
    id: 9,
    name: "Kogen Dojo - Severna Park",
    featured: false,
    description: "Professor Dwayne Bowie (Black Belt)",
    address: "549 Baltimore Annapolis Blvd ",
    phone: "410 544 8114",
  },
  {
    id: 10,
    name: "Lloyd Irvin's Mixed Martial Arts ",
    featured: false,
    description: "Professor Lloyd Irvin (Black Belt)",
    address: "6333 Old Branch Ave #302, Temple Hills, MD 20748",
    phone: "(301) 449-5425",
  },
  {
    id: 11,
    name: "Noel Smith Brazilian Jiu Jitsu ",
    featured: false,
    description: "Professor Noel Smith (Black Belt)",
    address: "7478 Baltimore Annapolis Blvd, Glen Burnie, MD 21061",
    phone: "(443) 354-3286",
  },
  {
    id: 12,
    name: "Team Randori Martial Arts ",
    featured: false,
    description: "Professor Carlos Placido (Black Belt)",
    address: "910 Bestgate Rd E, Annapolis, MD 21401",
    phone: "(443) 569-7070",
  },
  {
    id: 13,
    name: "Yamasaki Academy ",
    featured: false,
    description: "Professor Fernando Yamasaki (Black Belt)",
    address: "12712 Rock Creek Mill Rd, Rockville, MD 20853",
    phone: "(301) 770-0969",
  },
];
